### ISSUE TITLE
Version 1.3.0 - Roadmap (Updated on 2022-11-02)

### ISSUE THREAD

**Issue by SamBrishes** [RatMD/newshub-theme#2]
A small roadmap for Version 1.3.0

- [x] Additional Plugin support
  - [x] Support for BlakeJones.MagicForms plugin
  - [x] Support for JanVince.SmallContactForm plugin
  - [x] Support for JanVince.SmallGDPR plugin
  - [x] Support for RainLab.BlogVideoExtension plugin
  - [x] Support for RainLab.Forum plugin
  - [x] Support for RainLab.User plugin
- [x] Additional Theme options
  - [x] Improvements and Changes on both headers: Condensed& Extended
  - [x] New Sidebar Builder (with additional widgets)
      - [x] Related Posts widget
      - [x] Comment List widget
      - [x] Image w/ Text widget
  - [x] Optional sidebar for archive pages
  - [x] Add new structure on all existing content elements
  - [x] New Customization Options
  - [x] Update Meta Tags / clean-up header and footer areas
- [x] Bootstrap Stylings
  - [x] Update bootstrap dropdown design (to fit own dropdown design)
  - [x] Improved dark mode for all native bootstrap elements (using Bootstrap's new color-mode)
- [x] Change JS Bundler from rollup to esBuild
- [x] Dependencies
  - [x] Update Dependencies (Bootstrap & Keen-Slider --- Bootstrap Lightbox will be replaced)
  - [x] Replace Bootstrap Lightbox
- [x] Documentation on demonstration page

You can also write down your wishes here, if possible I will try to include them in the new update.

**Comment by SamDeny** [comment]
Status Update: Currently working on the new header stylings and structure. 

![status-update](https://user-images.githubusercontent.com/106578633/194839379-b23b5353-e679-4f83-94f7-fdad7424e64a.PNG)

**Comment by SamDeny** [comment]
Unfortunately, I didn't had much spare time left in the last few weeks... however... I'm still working on the new v1.3.0 release, including an improved page builder

__Before it looked like this...__

![before](https://user-images.githubusercontent.com/106578633/199366639-ca65bdc2-05e9-48ab-ad95-10352411d741.PNG)


__Now it's more like this...__

![after](https://user-images.githubusercontent.com/106578633/199366647-3c8e8a7a-412a-4466-a28f-cc2cd198394e.PNG)

This is not only more compact, but also be included with every content element (soon), providing a better customization without relying to a section as parent.
